import { apiFetch } from "./client";

export type AlertSeverity = "info" | "warning" | "error" | "critical";
export type AlertStatus = "open" | "acknowledged" | "resolved" | "muted";
export type AlertEvidence = { metric: string; actual_value: string | number | boolean | null; threshold_value: string | number | boolean | null; related_task_id: string | null; related_event_id: string | null; related_file: string | null; pending_operation: string | null };
export type WorkflowAlert = { alert_id: string; rule_id: string; rule_code: string; thread_id: string; branch_id: string; project_name: string | null; category: string; severity: AlertSeverity; status: AlertStatus; title: string; message: string; fingerprint: string; first_detected_at: string; last_detected_at: string; occurrence_count: number; acknowledged_at: string | null; acknowledged_by: string | null; resolved_at: string | null; resolved_by: string | null; resolution_note: string | null; muted_until: string | null; current_evidence: AlertEvidence; primary_event_id: string | null; related_task_id: string | null; related_file: string | null; created_at: string; updated_at: string };
export type AlertCounts = Record<AlertStatus | AlertSeverity, number>;
export type AlertListResponse = { items: WorkflowAlert[]; total: number; limit: number; offset: number; has_more: boolean; counts: AlertCounts };
export type AlertSummary = { open_total: number; acknowledged_total: number; resolved_total: number; muted_total: number; critical_open: number; error_open: number; warning_open: number; info_open: number; affected_workflows: number; top_rules: { key: string; label: string; count: number; percentage: number | null }[]; average_time_to_acknowledge_seconds: number | null; average_time_to_resolve_seconds: number | null; oldest_open_alert_seconds: number | null; calculated_at: string };
export type AlertRule = { rule_id: string; code: string; name: string; description: string; category: string; enabled: boolean; default_severity: AlertSeverity; threshold: { warning: number | null; error: number | null; critical: number | null } | null; cooldown_seconds: number; auto_resolve: boolean; branch_scope: "original" | "all"; created_at: string; updated_at: string | null };
export type AlertDetail = { alert: WorkflowAlert; occurrences: { occurrence_id: string; detected_at: string; severity: AlertSeverity; message: string; evidence: AlertEvidence; source_event_id: string | null }[]; actions: { action_id: string; action: string; actor: string | null; note: string | null; previous_status: AlertStatus | null; new_status: AlertStatus | null; created_at: string }[]; rule: AlertRule; navigation: { workflow: string; evaluation: string | null; timeline: string | null; execution: string | null; project: string | null }; notification_deliveries?: Array<Record<string, unknown>> };

export const getAlerts = (params: URLSearchParams, signal?: AbortSignal) => apiFetch<AlertListResponse>(`/api/alerts?${params}`, { signal });
export const getAlertSummary = (signal?: AbortSignal) => apiFetch<AlertSummary>("/api/alerts/summary", { signal });
export const getAlertDetail = (alertId: string, signal?: AbortSignal) => apiFetch<AlertDetail>(`/api/alerts/${encodeURIComponent(alertId)}`, { signal });
export const getAlertRules = (signal?: AbortSignal) => apiFetch<{ items: AlertRule[]; total: number }>("/api/alerts/rules?limit=100", { signal });
export const updateAlertRule = (ruleId: string, update: Partial<Pick<AlertRule, "enabled" | "threshold" | "cooldown_seconds" | "auto_resolve" | "default_severity" | "branch_scope">>) => apiFetch<AlertRule>(`/api/alerts/rules/${encodeURIComponent(ruleId)}`, { method: "PATCH", body: JSON.stringify(update) });
export const resetAlertRule = (ruleId: string) => apiFetch<AlertRule>(`/api/alerts/rules/${encodeURIComponent(ruleId)}/reset`, { method: "POST", body: "{}" });
export const actOnAlert = (alertId: string, action: "acknowledge" | "resolve" | "reopen" | "mute" | "unmute", durationSeconds?: number) => apiFetch<WorkflowAlert>(`/api/alerts/${encodeURIComponent(alertId)}/${action}`, { method: "POST", body: JSON.stringify({ actor: "local-user", ...(durationSeconds ? { duration_seconds: durationSeconds } : {}) }) });
