import { AlertTriangle, Check, Clock, RefreshCw, Volume2, VolumeX } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { actOnAlert, getAlertDetail, getAlertRules, resetAlertRule, updateAlertRule, type AlertDetail, type AlertRule, type WorkflowAlert } from "../api/alerts";
import { AppNavigation } from "../components/AppNavigation";
import { NotificationNavigation } from "../components/NotificationNavigation";
import { useAlerts } from "../hooks/useAlerts";
import { useAlertSummary } from "../hooks/useAlertSummary";
import { workflowAlertUrl } from "../utils/alertNavigation";

const severities = ["", "critical", "error", "warning", "info"];
const statuses = ["open,acknowledged", "open", "acknowledged", "resolved", "muted", "all"];
const testingRuleCodes = new Set(["HIGH_WARNING_COUNT", "TESTS_FAILED", "REPAIR_FAILED"]);

function isSafeTestingFile(alert: WorkflowAlert) {
  if (!testingRuleCodes.has(alert.rule_code) || !alert.related_file) return false;
  const path = alert.related_file.replaceAll("\\", "/");
  const name = path.split("/").at(-1) || "";
  return path.startsWith("tests/") && name.startsWith("test_") && name.endsWith(".py");
}

export function AlertsPage() {
  const [params, setParams] = useSearchParams();
  const apiParams = new URLSearchParams(params); if (!apiParams.has("status")) apiParams.set("status", "open,acknowledged");
  const { data, setData, loading, error, refresh } = useAlerts(apiParams);
  const { summary } = useAlertSummary();
  const [detail, setDetail] = useState<AlertDetail | null>(null); const [busy, setBusy] = useState<string | null>(null); const [rules, setRules] = useState<AlertRule[]>([]);
  const tab = params.get("view") || "alerts";
  useEffect(() => { if (tab === "rules") void getAlertRules().then((response) => setRules(response.items)); }, [tab]);
  const filter = (name: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(name, value); else next.delete(name); next.delete("offset"); setParams(next, { replace: true }); };
  const action = async (alert: WorkflowAlert, name: "acknowledge" | "resolve" | "reopen" | "mute" | "unmute") => {
    if (name === "resolve" && alert.severity === "critical" && !window.confirm("¿Resolver esta alerta crítica?")) return;
    setBusy(alert.alert_id); const previous = data;
    if (data) setData({ ...data, items: data.items.map((item) => item.alert_id === alert.alert_id ? { ...item, status: name === "acknowledge" ? "acknowledged" : name === "resolve" ? "resolved" : name === "mute" ? "muted" : "open" } : item) });
    try { await actOnAlert(alert.alert_id, name, name === "mute" ? 3600 : undefined); await refresh(true); }
    catch { setData(previous); }
    finally { setBusy(null); }
  };
  return <div className="app-shell alerts-page"><AppNavigation /><main>
    <header className="alerts-heading"><div><p className="page-eyebrow">Operación</p><h1>Alertas</h1><p>{summary ? `${summary.critical_open} críticas · ${summary.error_open} errores · ${summary.warning_open} warnings` : "Incidentes operativos durables"}</p></div><button className="icon-button" aria-label="Actualizar alertas" title="Actualizar alertas" onClick={() => void refresh()}><RefreshCw aria-hidden="true" /></button></header>
    <NotificationNavigation />
    {tab === "rules" ? <section className="alert-rules" aria-label="Reglas de alerta">{rules.map((rule) => <article key={rule.rule_id}><div><strong>{rule.code}</strong><p>{rule.description}</p></div><label>Threshold<input aria-label={`Threshold ${rule.code}`} type="number" value={rule.threshold?.warning ?? ""} onChange={(event) => setRules((current) => current.map((item) => item.rule_id === rule.rule_id ? { ...item, threshold: { warning: Number(event.target.value), error: item.threshold?.error ?? null, critical: item.threshold?.critical ?? null } } : item))} /></label><label>Cooldown<input aria-label={`Cooldown ${rule.code}`} type="number" value={rule.cooldown_seconds} onChange={(event) => setRules((current) => current.map((item) => item.rule_id === rule.rule_id ? { ...item, cooldown_seconds: Number(event.target.value) } : item))} /></label><label className="toggle"><input type="checkbox" checked={rule.enabled} onChange={async (event) => { if (!event.target.checked && rule.default_severity === "critical" && !window.confirm("¿Desactivar esta regla crítica?")) return; const updated = await updateAlertRule(rule.rule_id, { enabled: event.target.checked }); setRules((current) => current.map((item) => item.rule_id === updated.rule_id ? updated : item)); }} />Activa</label><button onClick={async () => { if (window.confirm("¿Restaurar los valores por defecto?")) { const reset = await resetAlertRule(rule.rule_id); setRules((current) => current.map((item) => item.rule_id === reset.rule_id ? reset : item)); } }}>Restaurar</button><button onClick={async () => { const updated = await updateAlertRule(rule.rule_id, { threshold: rule.threshold, cooldown_seconds: rule.cooldown_seconds }); setRules((current) => current.map((item) => item.rule_id === updated.rule_id ? updated : item)); }}>Guardar</button></article>)}</section> : <>
      <section className="alert-summary" aria-label="Resumen de alertas"><div><strong>{summary?.critical_open ?? 0}</strong><span>Críticas</span></div><div><strong>{summary?.error_open ?? 0}</strong><span>Errores</span></div><div><strong>{summary?.warning_open ?? 0}</strong><span>Warnings</span></div><div><strong>{summary?.affected_workflows ?? 0}</strong><span>Workflows afectados</span></div></section>
      <section className="alert-filters" aria-label="Filtros de alertas"><label>Estado<select value={params.get("status") || "open,acknowledged"} onChange={(e) => filter("status", e.target.value)}>{statuses.map((item) => <option key={item} value={item}>{item === "all" ? "Todos" : item}</option>)}</select></label><label>Severidad<select value={params.get("severity") || ""} onChange={(e) => filter("severity", e.target.value)}>{severities.map((item) => <option key={item} value={item}>{item || "Todas"}</option>)}</select></label><label>Regla<input value={params.get("rule_code") || ""} onChange={(e) => filter("rule_code", e.target.value)} /></label><label>Proyecto<input value={params.get("project_name") || ""} onChange={(e) => filter("project_name", e.target.value)} /></label><label>Buscar<input type="search" value={params.get("search") || ""} onChange={(e) => filter("search", e.target.value)} /></label></section>
      {loading && !data && <div className="alerts-state" role="status"><span className="loading-spinner" />Cargando alertas...</div>}{error && <div className="alerts-state" role="alert"><AlertTriangle aria-hidden="true" />{error}<button onClick={() => void refresh()}>Reintentar</button></div>}{data && !data.items.length && <div className="alerts-state"><Check aria-hidden="true" />No hay alertas para estos filtros.</div>}
      <section className="alert-list" aria-label="Lista de alertas">{data?.items.map((alert) => <article className="alert-card" data-severity={alert.severity} key={alert.alert_id}><header><span className="alert-severity"><AlertTriangle aria-hidden="true" />{alert.severity}</span><span className="alert-status">{alert.status}</span><strong>{alert.title}</strong></header><p>{alert.project_name || alert.thread_id} · {new Date(alert.last_detected_at).toLocaleString("es-PE")}</p><p>{alert.message}</p><small>{alert.rule_code} · {alert.occurrence_count} ocurrencias</small><footer><Link to={workflowAlertUrl(alert)}>Ver workflow</Link>{alert.category === "evaluation" || alert.category === "testing" ? <Link to={workflowAlertUrl(alert, "evaluation")}>Evaluation</Link> : null}{testingRuleCodes.has(alert.rule_code) && alert.related_task_id ? <Link to={workflowAlertUrl(alert, "execution")}>Ver tarea</Link> : null}{alert.primary_event_id && <Link to={workflowAlertUrl(alert, "timeline")}>{testingRuleCodes.has(alert.rule_code) ? "Ver en Timeline" : "Timeline"}</Link>}{isSafeTestingFile(alert) ? <Link to={workflowAlertUrl(alert, "project")}>Ver archivo</Link> : null}<button disabled={busy === alert.alert_id} onClick={() => void getAlertDetail(alert.alert_id).then(setDetail)}>Detalle</button>{alert.status === "open" && <button disabled={busy === alert.alert_id} onClick={() => void action(alert, "acknowledge")}><Check aria-hidden="true" />Reconocer</button>}{alert.status !== "resolved" && <button disabled={busy === alert.alert_id} onClick={() => void action(alert, "resolve")}>Resolver</button>}{alert.status === "resolved" && <button disabled={busy === alert.alert_id} onClick={() => void action(alert, "reopen")}><RefreshCw aria-hidden="true" />Reabrir</button>}{alert.status === "muted" ? <button disabled={busy === alert.alert_id} onClick={() => void action(alert, "unmute")}><Volume2 aria-hidden="true" />Reactivar</button> : alert.status !== "resolved" && <button disabled={busy === alert.alert_id} onClick={() => void action(alert, "mute")}><VolumeX aria-hidden="true" />Silenciar</button>}</footer></article>)}</section>
      {data && data.total > data.limit && <nav className="alert-pagination" aria-label="Paginación"><button disabled={!Number(params.get("offset") || 0)} onClick={() => filter("offset", String(Math.max(Number(params.get("offset") || 0) - data.limit, 0)))}>Anterior</button><button disabled={!data.has_more} onClick={() => filter("offset", String(Number(params.get("offset") || 0) + data.limit))}>Siguiente</button></nav>}
      {detail && <div className="alert-dialog-backdrop" role="presentation" onMouseDown={() => setDetail(null)}><section className="alert-dialog" role="dialog" aria-modal="true" aria-labelledby="alert-detail-title" onMouseDown={(e) => e.stopPropagation()}><header><div><span>{detail.alert.severity} · {detail.alert.status}</span><h2 id="alert-detail-title">{detail.alert.title}</h2></div><button aria-label="Cerrar detalle" onClick={() => setDetail(null)}>×</button></header><dl><dt>Regla</dt><dd>{detail.rule.code}</dd><dt>Branch</dt><dd>{detail.alert.branch_id}</dd><dt>Evidencia</dt><dd>{detail.alert.current_evidence.metric}: {String(detail.alert.current_evidence.actual_value)}</dd></dl><h3>Ocurrencias</h3><ol>{detail.occurrences.map((item) => <li key={item.occurrence_id}><Clock aria-hidden="true" />{new Date(item.detected_at).toLocaleString("es-PE")} · {item.message}</li>)}</ol><h3>Acciones</h3><ol>{detail.actions.map((item) => <li key={item.action_id}>{item.action} · {item.actor || "system"}</li>)}</ol><h3>Entregas</h3>{detail.notification_deliveries?.length ? <ol>{detail.notification_deliveries.map((item) => <li key={String(item.delivery_id)}>{String(item.alert_event)} · {String(item.status)}</li>)}</ol> : <p>Sin entregas.</p>}</section></div>}
    </>}
  </main></div>;
}
