import { Activity, AlertTriangle, BarChart3, Bell, CheckCircle2, Clock3, RefreshCw, RotateCcw, TestTube2, Users } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { AppNavigation } from "../components/AppNavigation";
import { getDashboardActivity, getDashboardAgents, getDashboardAttention, getDashboardSummary, getDashboardTimeSeries, type ActivityItem, type AgentMetric, type AttentionItem, type DashboardFilters, type DashboardSummary, type DashboardTimeSeries } from "../api/dashboard";
import { useAlertSummary } from "../hooks/useAlertSummary";
import { useNotificationSummary } from "../hooks/useNotificationSummary";
import { getObservabilitySummary, type ObservabilitySummary } from "../api/observability";

const statuses = ["all", "completed", "running", "waiting", "failed", "cancelled"];
const grades = ["all", "excellent", "good", "acceptable", "poor", "critical"];
const metrics = [["workflow_count", "Workflows creados"], ["completed_count", "Completados"], ["failed_count", "Fallidos"], ["success_rate", "Tasa de éxito"], ["average_score", "Score promedio"], ["average_duration", "Duración promedio"], ["average_active_duration", "Duración activa"], ["average_approval_wait", "Espera de aprobación"], ["tests_passed", "Tests aprobados"], ["tests_failed", "Tests fallidos"], ["repair_count", "Reparaciones"], ["warning_count", "Warnings"]] as const;
const dateInput = (daysAgo: number) => { const date = new Date(); date.setDate(date.getDate() - daysAgo); return date.toISOString().slice(0, 10); };
const isoBoundary = (value: string, end = false) => value ? `${value}T${end ? "23:59:59.999" : "00:00:00"}Z` : undefined;
const duration = (value: number | null | undefined) => value == null ? "n/a" : value < 60 ? `${Math.round(value)} s` : `${(value / 60).toFixed(1)} min`;
const number = (value: number | null | undefined, suffix = "") => value == null ? "n/a" : `${Number(value.toFixed(1)).toLocaleString("es-PE")}${suffix}`;

function Kpi({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: typeof Activity }) {
  return <article className="dashboard-kpi"><Icon aria-hidden="true" /><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>;
}
function BarSeries({ series }: { series: DashboardTimeSeries }) {
  const max = Math.max(...series.points.map((point) => point.value ?? 0), 1);
  const formatter = new Intl.DateTimeFormat("es-PE", { dateStyle: "short", timeStyle: "short", timeZone: series.timezone });
  return <div className="dashboard-bars" role="img" aria-label={`Serie ${series.metric}, ${series.points.length} periodos`}>{series.points.map((point) => <div className="dashboard-bar-slot" key={point.bucket_start} data-bucket-start={point.bucket_start} data-bucket-end={point.bucket_end} title={`${formatter.format(new Date(point.bucket_start))} - ${formatter.format(new Date(point.bucket_end))}: ${point.value ?? "Sin datos"}`}><span style={{ height: `${Math.max((point.value ?? 0) / max * 100, point.value ? 4 : 1)}%` }} /></div>)}</div>;
}

export function DashboardPage() {
  const { summary: alertSummary } = useAlertSummary();
  const { summary: notificationSummary } = useNotificationSummary();
  const [params, setParams] = useSearchParams();
  const [summary, setSummary] = useState<DashboardSummary | null>(null);
  const [observability, setObservability] = useState<ObservabilitySummary | null>(null);
  const [series, setSeries] = useState<DashboardTimeSeries | null>(null);
  const [agents, setAgents] = useState<AgentMetric[]>([]); const [attention, setAttention] = useState<AttentionItem[]>([]); const [activity, setActivity] = useState<ActivityItem[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const metric = params.get("metric") || "workflow_count";
  const filters = useMemo<DashboardFilters>(() => ({ dateFrom: isoBoundary(params.get("from") || dateInput(30)), dateTo: isoBoundary(params.get("to") || dateInput(0), true), status: params.get("status") || "all", projectName: params.get("project") || undefined, workflowIntent: params.get("intent") || undefined, framework: params.get("framework") || undefined, grade: params.get("grade") || "all", branchScope: (params.get("branches") as "original" | "all") || "original", scoringVersion: params.get("scoring") || "latest", timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC" }), [params]);
  const load = useCallback(async (background = false) => {
    if (!background) setLoading(true);
    try { const [s, ts, ag, at, ac, obs] = await Promise.all([getDashboardSummary(filters), getDashboardTimeSeries(filters, metric, "day"), getDashboardAgents(filters), getDashboardAttention(filters), getDashboardActivity(filters), getObservabilitySummary().catch(() => null)]); setSummary(s); setSeries(ts); setAgents(ag.items); setAttention(at.items); setActivity(ac.items); setObservability(obs); setError(null); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo cargar el dashboard."); }
    finally { if (!background) setLoading(false); }
  }, [filters, metric]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { const poll = () => document.visibilityState === "visible" && void load(true); const timer = window.setInterval(poll, 30_000); document.addEventListener("visibilitychange", poll); return () => { window.clearInterval(timer); document.removeEventListener("visibilitychange", poll); }; }, [load]);
  const setFilter = (name: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(name, value); else next.delete(name); setParams(next, { replace: true }); };
  const empty = summary?.workflow_counts.total === 0;

  return <div className="app-shell dashboard-page"><AppNavigation /><main>
    {alertSummary && <section className="dashboard-alert-kpi"><Bell aria-hidden="true" /><div><span>Alertas activas</span><strong>{alertSummary.open_total + alertSummary.acknowledged_total}</strong><small>{alertSummary.critical_open} críticas · {alertSummary.error_open} errores · {alertSummary.affected_workflows} workflows</small></div><Link to="/alerts">Ver alertas</Link></section>}
    {notificationSummary && <section className="dashboard-alert-kpi" data-severity={notificationSummary.dead_letter ? "critical" : "normal"}><Bell aria-hidden="true" /><div><span>Entregas de notificación</span><strong>{notificationSummary.deliveries_last_24h}</strong><small>{notificationSummary.dead_letter} dead letters · {notificationSummary.failed} fallidas · {notificationSummary.channels_misconfigured} canales sin configurar</small></div><Link to="/notifications/deliveries">Ver entregas</Link></section>}
    {observability && <section className="dashboard-alert-kpi observability-dashboard-link"><Activity aria-hidden="true" /><div><span>Observabilidad</span><strong>{observability.traces}</strong><small>{observability.errors} errores · {observability.slow_spans} spans lentos</small></div><Link to="/observability">Explorar trazas</Link></section>}
    <div className="dashboard-heading"><div><p className="page-eyebrow">Operacion global</p><h1>Dashboard</h1><p>Salud, calidad y rendimiento de la Software Factory.</p></div><button className="icon-button" title="Actualizar dashboard" aria-label="Actualizar dashboard" onClick={() => void load()}><RefreshCw aria-hidden="true" /></button></div>
    <section className="dashboard-filters" aria-label="Filtros del dashboard"><label>Desde<input type="date" value={params.get("from") || dateInput(30)} onChange={(e) => setFilter("from", e.target.value)} /></label><label>Hasta<input type="date" value={params.get("to") || dateInput(0)} onChange={(e) => setFilter("to", e.target.value)} /></label><label>Estado<select value={filters.status} onChange={(e) => setFilter("status", e.target.value)}>{statuses.map((item) => <option key={item} value={item}>{item === "all" ? "Todos" : item}</option>)}</select></label><label>Proyecto<input value={params.get("project") || ""} placeholder="Nombre" onChange={(e) => setFilter("project", e.target.value)} /></label><label>Framework<input value={params.get("framework") || ""} placeholder="Todos" onChange={(e) => setFilter("framework", e.target.value)} /></label><label>Calidad<select value={filters.grade} onChange={(e) => setFilter("grade", e.target.value)}>{grades.map((item) => <option key={item} value={item}>{item === "all" ? "Todas" : item}</option>)}</select></label><label>Ramas<select value={filters.branchScope} onChange={(e) => setFilter("branches", e.target.value)}><option value="original">Solo original</option><option value="all">Todas</option></select></label><button className="secondary-button" onClick={() => setParams({}, { replace: true })}><RotateCcw aria-hidden="true" />Restablecer</button></section>
    {loading && !summary && <div className="dashboard-state"><span className="loading-spinner" />Cargando metricas...</div>}{error && <div className="dashboard-state error-banner" role="alert"><AlertTriangle aria-hidden="true" />{error}<button onClick={() => void load()}>Reintentar</button></div>}{empty && <div className="dashboard-state"><BarChart3 aria-hidden="true" /><strong>Sin datos para estos filtros</strong><span>Ajusta el periodo o crea un workflow.</span></div>}
    {summary && !empty && <><section className="dashboard-kpis"><Kpi icon={Activity} label="Workflows" value={number(summary.workflow_counts.total)} detail={`${summary.workflow_counts.completed} completados · ${number(summary.workflow_counts.success_rate_percent, "%")} éxito`} /><Kpi icon={BarChart3} label="Score promedio" value={number(summary.scores.average_score, "/100")} detail={`${summary.scores.evaluated_workflows} evaluados · ${summary.scores.provisional} provisionales`} /><Kpi icon={CheckCircle2} label="Tests aprobados" value={number(summary.testing.pass_rate_percent, "%")} detail={`${summary.testing.passed} de ${summary.testing.executed}`} /><Kpi icon={Clock3} label="Duración P50" value={duration(summary.durations.p50_wall_clock_seconds)} detail={`P90 ${duration(summary.durations.p90_wall_clock_seconds)} · P95 ${duration(summary.durations.p95_wall_clock_seconds)}`} /><Kpi icon={TestTube2} label="Reparaciones" value={number(summary.testing.repair_successful)} detail={`${summary.testing.repair_required} requeridas`} /><Kpi icon={AlertTriangle} label="Aprobaciones pendientes" value={number(summary.approvals.workflows_with_pending_approval)} detail={`${summary.approvals.total_approvals_rejected} rechazos`} /></section>
    <section className="dashboard-grid dashboard-grid-main"><article className="dashboard-panel dashboard-chart-panel"><header><div><h2>Evolución</h2><p>{metrics.find(([key]) => key === metric)?.[1]}</p></div><select aria-label="Métrica de evolución" value={metric} onChange={(e) => setFilter("metric", e.target.value)}>{metrics.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></header>{series && <BarSeries series={series} />}</article><article className="dashboard-panel"><header><div><h2>Distribución</h2><p>Estado y calidad final</p></div></header><div className="distribution-list">{Object.entries(summary.workflow_counts).filter(([key]) => ["completed", "running", "waiting", "pending", "failed", "cancelled"].includes(key)).map(([key, value]) => <div key={key}><span>{key}</span><strong>{value}</strong><i style={{ width: `${Number(value) / Math.max(summary.workflow_counts.total, 1) * 100}%` }} /></div>)}</div><div className="grade-row">{(["excellent", "good", "acceptable", "poor", "critical"] as const).map((grade) => <span key={grade}>{grade}<strong>{summary.scores[grade]}</strong></span>)}</div></article></section>
    <section className="dashboard-grid dashboard-grid-equal"><article className="dashboard-panel"><header><div><h2>Atención requerida</h2><p>Ordenada por impacto</p></div></header>{attention.length ? <ul className="attention-list">{attention.map((item) => <li key={`${item.thread_id}-${item.branch_id}`} data-severity={item.severity}><Link to={`/workflows/${item.thread_id}`}>{item.project_name || item.thread_id}</Link><span>{item.severity}: {item.reasons.join(", ")}{item.pending_operation ? ` · ${item.pending_operation}` : ""}</span><strong>{item.score ?? "n/a"}</strong></li>)}</ul> : <p className="panel-empty">No hay workflows que requieran atención.</p>}</article><article className="dashboard-panel"><header><div><h2>Rendimiento por agente</h2><p>Ejecuciones agregadas</p></div><Users aria-hidden="true" /></header><div className="table-scroll"><table><thead><tr><th>Agente</th><th>Tareas</th><th>Completadas</th><th>Fallidas</th><th>Éxito</th><th>Intentos</th><th>Workflows</th><th>Archivos</th></tr></thead><tbody>{agents.map((agent) => <tr key={agent.agent}><td>{agent.agent}</td><td>{agent.total_tasks}</td><td>{agent.completed_tasks}</td><td>{agent.failed_tasks}</td><td>{number(agent.completion_rate_percent, "%")}</td><td>{number(agent.average_attempts)}</td><td>{agent.related_workflows}</td><td>{agent.related_files}</td></tr>)}</tbody></table></div></article></section>
    <section className="dashboard-grid dashboard-grid-equal"><article className="dashboard-panel"><header><div><h2>Hallazgos frecuentes</h2><p>Señales de calidad repetidas</p></div></header><ol className="rank-list">{summary.top_findings.map((item) => <li key={item.key}><span>{item.label}</span><strong>{item.count}</strong></li>)}</ol>{!summary.top_findings.length && <p className="panel-empty">Sin hallazgos registrados.</p>}</article><article className="dashboard-panel"><header><div><h2>Actividad reciente</h2><p>Eventos operativos resumidos</p></div></header><ul className="activity-list">{activity.map((item) => <li key={item.event_id}><span className={`activity-dot ${item.status}`} /><div><Link to={`/workflows/${item.thread_id}`}>{item.message}</Link><small>{new Date(item.timestamp).toLocaleString("es-PE")}</small></div></li>)}</ul></article></section><footer className="dashboard-meta">Calculado {new Date(summary.calculated_at).toLocaleString("es-PE")} · scoring {summary.scores.scoring_versions.join(", ") || "sin evaluación"}{!summary.data_complete ? " · datos parciales" : ""}</footer></>}
  </main></div>;
}
