import { AlertTriangle, Check, Eye, Play, Plus, RefreshCw, RotateCcw, Trash2, X } from "lucide-react";
import { type FormEvent, type ReactNode, useCallback, useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import {
  createChannel, createPolicy, deleteChannel, deletePolicy, deliveryAction,
  getChannels, getDeliveries, getDelivery, getEscalations, getInbox,
  getPolicies, getQuietHours, markAllNotificationsRead, markNotificationRead,
  testChannel, updateChannel, updatePolicy, type DeliveryDetail,
  type DeliveryList, type EscalationPolicy, type NotificationChannel, type NotificationPolicy,
} from "../api/notifications";
import { AppNavigation } from "../components/AppNavigation";
import { EscalationPoliciesPanel } from "../components/EscalationPoliciesPanel";
import { NotificationNavigation } from "../components/NotificationNavigation";

function PageFrame({ title, description, children }: { title: string; description: string; children: ReactNode }) {
  return <div className="app-shell notifications-page"><AppNavigation /><main><header className="alerts-heading"><div><p className="page-eyebrow">Operación</p><h1>{title}</h1><p>{description}</p></div></header><NotificationNavigation />{children}</main></div>;
}

function State({ loading, error, empty }: { loading: boolean; error: string | null; empty?: boolean }) {
  if (loading) return <div className="alerts-state" role="status"><span className="loading-spinner" />Cargando...</div>;
  if (error) return <div className="alerts-state" role="alert"><AlertTriangle aria-hidden="true" />{error}</div>;
  if (empty) return <div className="alerts-state"><Check aria-hidden="true" />No hay resultados.</div>;
  return null;
}

export function NotificationChannelsPage() {
  const [channels, setChannels] = useState<NotificationChannel[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [showForm, setShowForm] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [inbox, setInbox] = useState<Awaited<ReturnType<typeof getInbox>> | null>(null);
  const load = useCallback(async () => { try { setChannels(await getChannels()); setInbox(await getInbox()); setError(null); } catch (caught) { setError((caught as Error).message); } finally { setLoading(false); } }, []);
  useEffect(() => { void Promise.resolve().then(() => load()); }, [load]);
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const type = String(form.get("type"));
    await createChannel({ name: String(form.get("name")), channel_type: type, secret_reference: String(form.get("secret")) || null, configuration: form.get("url") ? { url: String(form.get("url")) } : {}, max_attempts: Number(form.get("attempts")), initial_backoff_seconds: 2, max_backoff_seconds: 300, timeout_seconds: 10, verify_tls: true });
    setShowForm(false); formElement.reset(); await load();
  };
  return <PageFrame title="Canales" description="Destinos durables y salud de entrega">
    <div className="notification-toolbar"><button onClick={() => setShowForm((value) => !value)}><Plus aria-hidden="true" />Crear canal</button><button className="icon-button" aria-label="Actualizar canales" title="Actualizar canales" onClick={() => void load()}><RefreshCw aria-hidden="true" /></button></div>
    {notice && <p className="notification-notice" role="status">{notice}</p>}
    {showForm && <form className="notification-form" aria-label="Crear canal" onSubmit={(event) => void submit(event)}><label>Nombre<input name="name" required maxLength={120} /></label><label>Tipo<select name="type"><option value="webhook">Webhook</option><option value="slack_webhook">Slack webhook</option><option value="teams_webhook">Teams webhook</option><option value="internal">Internal</option><option value="log">Log</option><option value="email">Email</option></select></label><label>Secret reference<input name="secret" placeholder="env:OPERATIONS_WEBHOOK_URL" /></label><label>URL de desarrollo<input name="url" type="url" placeholder="https://example.com/webhook" /></label><label>Intentos<input name="attempts" type="number" min="1" max="20" defaultValue="3" /></label><div><button type="submit">Guardar</button><button type="button" onClick={() => setShowForm(false)}>Cancelar</button></div></form>}
    <State loading={loading} error={error} empty={!channels.length} />
    <section className="notification-list" aria-label="Canales de notificación">{channels.map((channel) => <article className="notification-card" key={channel.channel_id}><header><div><strong>{channel.name}</strong><span>{channel.channel_type}</span></div><span className="delivery-status" data-status={channel.health}>{channel.health}</span></header><dl><dt>Estado</dt><dd>{channel.enabled ? "Activo" : "Pausado"}</dd><dt>Secret reference</dt><dd>{channel.secret_reference || "n/a"}</dd><dt>Configurada</dt><dd>{channel.secret_reference ? channel.secret_configured ? "sí" : "no" : "n/a"}</dd><dt>Configuración</dt><dd>{JSON.stringify(channel.configuration)}</dd></dl><footer><button onClick={async () => { if (channel.enabled && !window.confirm("¿Desactivar este canal?")) return; await updateChannel(channel.channel_id, { enabled: !channel.enabled }); await load(); }}>{channel.enabled ? "Desactivar" : "Activar"}</button><button onClick={async () => { if (!["internal", "log"].includes(channel.channel_type) && !window.confirm("¿Enviar una prueba real a este canal externo?")) return; const result = await testChannel(channel.channel_id); setNotice(`Prueba ${result.status}: ${result.delivery_id}`); }}> <Play aria-hidden="true" />Probar</button>{!channel.channel_id.startsWith("builtin:") && <button aria-label={`Eliminar ${channel.name}`} onClick={async () => { if (!window.confirm(`¿Eliminar ${channel.name}?`)) return; await deleteChannel(channel.channel_id); await load(); }}><Trash2 aria-hidden="true" /></button>}</footer></article>)}</section>
    <section className="notification-inbox"><header><div><h2>Inbox interno</h2><p>{inbox?.unread ?? 0} sin leer</p></div><button disabled={!inbox?.unread} onClick={async () => { await markAllNotificationsRead(); await load(); }}>Marcar todas leídas</button></header>{inbox?.items.map((item) => <div key={item.delivery_id} data-read={Boolean(item.read_at)}><Link to={`/alerts?search=${encodeURIComponent(item.alert_id)}`}>{item.alert_event} · {item.alert_id}</Link>{!item.read_at && <button aria-label={`Marcar leída ${item.delivery_id}`} onClick={async () => { await markNotificationRead(item.delivery_id); await load(); }}><Eye aria-hidden="true" /></button>}</div>)}</section>
  </PageFrame>;
}

const allSeverities = ["warning", "error", "critical"];
const allEvents = ["alert_opened", "alert_reopened", "alert_severity_escalated", "alert_resolved", "alert_auto_resolved", "alert_acknowledged"];
export function NotificationPoliciesPage() {
  const [policies, setPolicies] = useState<NotificationPolicy[]>([]); const [channels, setChannels] = useState<NotificationChannel[]>([]); const [quiet, setQuiet] = useState<Array<{ quiet_hours_id: string; name: string }>>([]); const [escalations, setEscalations] = useState<EscalationPolicy[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [showForm, setShowForm] = useState(false);
  const load = useCallback(async () => { try { const [p, c, q, e] = await Promise.all([getPolicies(), getChannels(), getQuietHours(), getEscalations()]); setPolicies(p); setChannels(c); setQuiet(q); setEscalations(e); setError(null); } catch (caught) { setError((caught as Error).message); } finally { setLoading(false); } }, []);
  useEffect(() => { void Promise.resolve().then(() => load()); }, [load]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await createPolicy({ name: String(form.get("name")), channel_ids: form.getAll("channels"), rule_codes: String(form.get("rules") || "").split(",").map((item) => item.trim()).filter(Boolean), severities: form.getAll("severities"), alert_events: form.getAll("events"), statuses: ["open", "acknowledged", "resolved"], branch_scope: form.get("branch"), project_name_pattern: String(form.get("project") || "") || null, cooldown_seconds: 0, send_resolved: form.has("resolved"), send_acknowledged: form.has("acknowledged"), quiet_hours_id: String(form.get("quiet") || "") || null, escalation_policy_id: String(form.get("escalation") || "") || null }); setShowForm(false); await load(); };
  return <PageFrame title="Políticas" description="Enrutamiento, silencio y escalamiento de alertas">
    <div className="notification-toolbar"><button onClick={() => setShowForm((value) => !value)}><Plus aria-hidden="true" />Crear política</button></div>
    {showForm && <form className="notification-form notification-policy-form" aria-label="Crear política" onSubmit={(event) => void submit(event)}><label>Nombre<input name="name" required /></label><fieldset><legend>Canales</legend>{channels.map((item) => <label key={item.channel_id}><input type="checkbox" name="channels" value={item.channel_id} />{item.name}</label>)}</fieldset><label>Reglas<input name="rules" placeholder="WORKFLOW_FAILED, TESTS_FAILED" /></label><fieldset><legend>Severidades</legend>{allSeverities.map((item) => <label key={item}><input defaultChecked type="checkbox" name="severities" value={item} />{item}</label>)}</fieldset><fieldset><legend>Eventos</legend>{allEvents.map((item) => <label key={item}><input defaultChecked={item !== "alert_acknowledged"} type="checkbox" name="events" value={item} />{item}</label>)}</fieldset><label>Branch<select name="branch"><option value="original">Original</option><option value="all">Todos</option></select></label><label>Proyecto<input name="project" placeholder="payments-*" /></label><label>Quiet hours<select name="quiet"><option value="">Ninguno</option>{quiet.map((item) => <option key={item.quiet_hours_id} value={item.quiet_hours_id}>{item.name}</option>)}</select></label><label>Escalamiento<select name="escalation"><option value="">Ninguno</option>{escalations.map((item) => <option key={item.escalation_policy_id} value={item.escalation_policy_id}>{item.name}</option>)}</select></label><label><input defaultChecked type="checkbox" name="resolved" />Notificar resolución</label><label><input type="checkbox" name="acknowledged" />Notificar acknowledge</label><div><button type="submit">Guardar</button><button type="button" onClick={() => setShowForm(false)}>Cancelar</button></div></form>}
    <State loading={loading} error={error} empty={!policies.length} /><section className="notification-list" aria-label="Políticas de notificación">{policies.map((policy) => <article className="notification-card" key={policy.policy_id}><header><div><strong>{policy.name}</strong><span>{policy.enabled ? "Activa" : "Pausada"}</span></div></header><p>Enviar alertas {policy.severities.join(", ")} de {policy.rule_codes.length ? policy.rule_codes.join(" y ") : "todas las reglas"} a {policy.channel_ids.map((id) => channels.find((item) => item.channel_id === id)?.name || id).join(", ")}.</p><small>{policy.branch_scope === "all" ? "Todos los branches" : "Solo original"}{policy.quiet_hours_id ? " · quiet hours" : ""}{policy.escalation_policy_id ? " · escalamiento" : ""}</small><footer><button onClick={async () => { if (policy.enabled && !window.confirm("¿Desactivar esta política?")) return; await updatePolicy(policy.policy_id, { enabled: !policy.enabled }); await load(); }}>{policy.enabled ? "Desactivar" : "Activar"}</button>{!policy.policy_id.startsWith("builtin:") && <button aria-label={`Eliminar ${policy.name}`} onClick={async () => { if (!window.confirm(`¿Eliminar ${policy.name}?`)) return; await deletePolicy(policy.policy_id); await load(); }}><Trash2 aria-hidden="true" /></button>}</footer></article>)}</section>
    <EscalationPoliciesPanel channels={channels} policies={escalations} onRefresh={load} />
  </PageFrame>;
}

const deliveryStatuses = ["", "pending", "processing", "delivered", "retry_scheduled", "dead_letter", "suppressed", "cancelled"];
export function NotificationDeliveriesPage() {
  const [params, setParams] = useSearchParams(); const [data, setData] = useState<DeliveryList | null>(null); const [detail, setDetail] = useState<DeliveryDetail | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const key=params.toString(); const load=useCallback(async(background=false)=>{if(!background)setLoading(true);try{setData(await getDeliveries(new URLSearchParams(key)));setError(null);}catch(caught){setError((caught as Error).message);}finally{if(!background)setLoading(false);}},[key]);
  useEffect(()=>{void Promise.resolve().then(()=>load());const timer=window.setInterval(()=>{if(document.visibilityState==="visible")void load(true);},10_000);return()=>window.clearInterval(timer);},[load]);
  const filter=(name:string,value:string)=>{const next=new URLSearchParams(params);if(value)next.set(name,value);else next.delete(name);next.delete("offset");setParams(next,{replace:true});};
  return <PageFrame title="Entregas" description="Cola, reintentos y dead letters durables">
    <div className="notification-toolbar"><label>Estado<select aria-label="Estado" value={params.get("status")||""} onChange={(event)=>filter("status",event.target.value)}>{deliveryStatuses.map((item)=><option value={item} key={item}>{item||"Todos"}</option>)}</select></label><label>Evento<input aria-label="Evento" value={params.get("alert_event")||""} onChange={(event)=>filter("alert_event",event.target.value)} /></label><label>Buscar<input aria-label="Buscar" type="search" value={params.get("search")||""} onChange={(event)=>filter("search",event.target.value)} /></label><button className="icon-button" aria-label="Actualizar entregas" onClick={()=>void load()}><RefreshCw aria-hidden="true" /></button></div>
    <State loading={loading} error={error} empty={Boolean(data&&!data.items.length)} />{data?.items.length ? <div className="notification-table-wrap"><table className="notification-table"><thead><tr><th>Estado</th><th>Canal</th><th>Alerta</th><th>Evento</th><th>Intentos</th><th>Programado</th><th>HTTP</th><th>Error</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{data.items.map((item)=><tr key={item.delivery_id} data-status={item.status}><td><span className="delivery-status" data-status={item.status}>{item.status}</span></td><td>{item.channel_id}</td><td><Link to={`/alerts?search=${encodeURIComponent(item.alert_id)}`}>{item.alert_id}</Link></td><td>{item.alert_event}</td><td>{item.attempt_count}/{item.max_attempts}</td><td>{new Date(item.scheduled_at).toLocaleString("es-PE")}</td><td>{item.response_status_code??"n/a"}</td><td>{item.last_error_code||"n/a"}</td><td><button aria-label={`Ver entrega ${item.delivery_id}`} onClick={()=>void getDelivery(item.delivery_id).then(setDetail)}><Eye aria-hidden="true" /></button>{["failed","dead_letter","cancelled"].includes(item.status)&&<button aria-label={`Reintentar ${item.delivery_id}`} onClick={async()=>{await deliveryAction(item.delivery_id,"retry");await load(true);}}><RotateCcw aria-hidden="true" /></button>}{["pending","retry_scheduled"].includes(item.status)&&<button aria-label={`Cancelar ${item.delivery_id}`} onClick={async()=>{await deliveryAction(item.delivery_id,"cancel");await load(true);}}><X aria-hidden="true" /></button>}</td></tr>)}</tbody></table></div>:null}
    {data&&data.total>data.limit?<nav className="alert-pagination" aria-label="Paginación"><button disabled={!Number(params.get("offset")||0)} onClick={()=>filter("offset",String(Math.max(Number(params.get("offset")||0)-data.limit,0)))}>Anterior</button><button disabled={!data.has_more} onClick={()=>filter("offset",String(Number(params.get("offset")||0)+data.limit))}>Siguiente</button></nav>:null}
    {detail&&<div className="alert-dialog-backdrop" role="presentation"><section className="alert-dialog delivery-dialog" role="dialog" aria-modal="true" aria-labelledby="delivery-title"><header><div><span>{detail.delivery.status}</span><h2 id="delivery-title">Detalle de entrega</h2></div><button aria-label="Cerrar detalle" onClick={()=>setDetail(null)}><X aria-hidden="true" /></button></header><dl><dt>Canal</dt><dd>{detail.channel?.name||detail.delivery.channel_id}</dd><dt>Política</dt><dd>{detail.policy?.name||detail.delivery.policy_id}</dd><dt>Fingerprint</dt><dd>{detail.delivery.fingerprint}</dd><dt>Error</dt><dd>{detail.delivery.last_error_message||"n/a"}</dd></dl><h3>Attempts</h3>{detail.attempts.length?<ol>{detail.attempts.map((attempt)=><li key={attempt.attempt_id}>#{attempt.attempt_number} · {attempt.result} · HTTP {attempt.response_status_code??"n/a"} · {attempt.duration_ms} ms</li>)}</ol>:<p>Sin intentos.</p>}<footer>{["failed","dead_letter","cancelled"].includes(detail.delivery.status)&&<button onClick={async()=>{await deliveryAction(detail.delivery.delivery_id,"retry");setDetail(null);await load(true);}}>Reintentar</button>}<button onClick={async()=>{if(!window.confirm("¿Crear una nueva entrega lógica?"))return;await deliveryAction(detail.delivery.delivery_id,"redeliver");setDetail(null);await load(true);}}>Reenviar</button></footer></section></div>}
  </PageFrame>;
}
