from enum import StrEnum


class WorkflowEventType(StrEnum):
    WORKFLOW_STARTED = "workflow_started"
    WORKFLOW_RESUMED = "workflow_resumed"
    WORKFLOW_FORKED = "workflow_forked"
    WORKFLOW_COMPLETED = "workflow_completed"
    WORKFLOW_FAILED = "workflow_failed"
    STAGE_STARTED = "stage_started"
    STAGE_COMPLETED = "stage_completed"
    STAGE_FAILED = "stage_failed"
    SUPERVISOR_DECISION_STARTED = "supervisor_decision_started"
    SUPERVISOR_DECISION_COMPLETED = "supervisor_decision_completed"
    SUPERVISOR_FALLBACK_USED = "supervisor_fallback_used"
    SUPERVISOR_LOOP_DETECTED = "supervisor_loop_detected"
    HANDOFF_COMPLETED = "handoff_completed"
    PLANNING_STARTED = "planning_started"
    PLANNING_COMPLETED = "planning_completed"
    PLANNING_FAILED = "planning_failed"
    WORKSPACE_INSPECTION_STARTED = "workspace_inspection_started"
    WORKSPACE_INSPECTION_COMPLETED = "workspace_inspection_completed"
    IMPLEMENTATION_STARTED = "implementation_started"
    IMPLEMENTATION_VALIDATION_COMPLETED = "implementation_validation_completed"
    IMPLEMENTATION_COMPLETED = "implementation_completed"
    IMPLEMENTATION_FAILED = "implementation_failed"
    TESTING_STARTED = "testing_started"
    TESTING_COMPLETED = "testing_completed"
    TESTING_FAILED = "testing_failed"
    REPAIR_STARTED = "repair_started"
    REPAIR_COMPLETED = "repair_completed"
    REPAIR_FAILED = "repair_failed"
    APPROVAL_REQUIRED = "approval_required"
    APPROVAL_GRANTED = "approval_granted"
    APPROVAL_REJECTED = "approval_rejected"
    TOOL_STARTED = "tool_started"
    TOOL_COMPLETED = "tool_completed"
    TOOL_FAILED = "tool_failed"
    TEST_RUN_STARTED = "test_run_started"
    TEST_RUN_COMPLETED = "test_run_completed"
    TEST_RUN_FAILED = "test_run_failed"
