import type {
  WorkflowAgentExecution,
  WorkflowEvaluation,
  WorkflowEvent,
  WorkflowSnapshot,
} from "../api/types";

export function workflowEvent(
  sequence = 1,
  overrides: Partial<WorkflowEvent> = {},
): WorkflowEvent {
  return {
    event_id: `event-${sequence}`,
    thread_id: "thread-1",
    sequence,
    type: "workflow_started",
    timestamp: "2026-07-26T12:00:00Z",
    source: "test",
    stage: "planning",
    status: "running",
    message: null,
    data: {},
    ...overrides,
  };
}

export function workflowEvaluation(
  overrides: Partial<WorkflowEvaluation> = {},
): WorkflowEvaluation {
  const category = {
    score: 20,
    max_score: 20,
    percentage: 100,
    evaluation_state: "evaluated" as const,
    available_points: 20,
    penalties: [],
    bonuses: [],
    positive_signals: [{
      code: "VALID",
      category: "planning",
      message: "Validación completada.",
      related_task_id: null,
      related_event_id: null,
      related_file: null,
    }],
    findings: [],
  };
  return {
    thread_id: "thread-1",
    branch_id: "original",
    lineage: "original",
    inherited_from_branch: null,
    origin_checkpoint: null,
    terminal_status: "completed",
    data_complete: true,
    evaluation_status: "final",
    overall_score: 92,
    max_score: 100,
    percentage: 92,
    earned_points: 92,
    available_points: 100,
    provisional_percentage: 92,
    projected_max_score: 100,
    is_provisional: false,
    final_grade_available: true,
    grade: "excellent",
    provisional_grade: null,
    planning: category,
    implementation: {
      ...category,
      score: 23,
      max_score: 25,
      available_points: 25,
      percentage: 92,
      penalties: [{
        code: "IMPLEMENTATION_RETRY",
        category: "implementation",
        points: -2,
        message: "Un intento adicional de implementación.",
        severity: "warning",
        related_task_id: "task-implementation",
        related_event_id: null,
        related_file: null,
      }],
    },
    testing: {
      ...category,
      score: 23,
      max_score: 25,
      available_points: 25,
      percentage: 92,
      penalties: [{
        code: "TEST_WARNINGS",
        category: "testing",
        points: -2,
        message: "2 warnings en la ejecución de pruebas.",
        severity: "warning",
        related_task_id: null,
        related_event_id: "event-test",
        related_file: "tests/test_health.py",
      }],
      findings: [{
        code: "TEST_WARNINGS",
        category: "testing",
        title: "Warnings de pruebas",
        description: "Pytest reportó 2 warnings.",
        severity: "warning",
        recommendation: "Revisar y eliminar warnings de pytest.",
        related_task_id: "task-qa",
        related_event_id: "event-test",
        related_file: "tests/test_health.py",
      }],
    },
    efficiency: {
      ...category,
      score: 13,
      max_score: 15,
      available_points: 15,
      percentage: 86.67,
    },
    reliability: {
      ...category,
      score: 13,
      max_score: 15,
      available_points: 15,
      percentage: 86.67,
    },
    requirement_coverage: {
      total: 1,
      satisfied: 1,
      unsatisfied: 0,
      unknown: 0,
      coverage_percent: 100,
      items: [{
        index: 1,
        text: "GET /health devuelve ok",
        status: "satisfied",
        evidence: ["tests_passed"],
        related_task_ids: ["task-implementation"],
        related_event_ids: ["event-test"],
        related_files: ["tests/test_health.py"],
      }],
    },
    acceptance_coverage: {
      total: 1,
      satisfied: 1,
      unsatisfied: 0,
      unknown: 0,
      coverage_percent: 100,
      items: [{
        index: 1,
        text: "La prueba de health pasa",
        status: "satisfied",
        evidence: ["tests_passed"],
        related_task_ids: ["task-qa"],
        related_event_ids: ["event-test"],
        related_files: ["tests/test_health.py"],
      }],
    },
    duration: {
      wall_clock_duration_seconds: 48,
      active_execution_seconds: 46.4,
      total_duration_seconds: 48,
      planning_seconds: 0.1,
      implementation_seconds: 45,
      testing_seconds: 1.3,
      repair_seconds: null,
      approval_wait_seconds: 1.6,
      finalize_seconds: 0.1,
      planning: { elapsed_seconds: 0.1, active_seconds: 0.1, waiting_seconds: 0 },
      implementation: { elapsed_seconds: 45, active_seconds: 43.4, waiting_seconds: 1.6 },
      testing: { elapsed_seconds: 1.3, active_seconds: 1.3, waiting_seconds: 0 },
      repair: { elapsed_seconds: null, active_seconds: null, waiting_seconds: null },
      finalize: { elapsed_seconds: 0.1, active_seconds: 0.1, waiting_seconds: 0 },
    },
    penalties: [],
    bonuses: [],
    positive_signals: [],
    findings: [{
      code: "TEST_WARNINGS",
      category: "testing",
      title: "Warnings de pruebas",
      description: "Pytest reportó 2 warnings.",
      severity: "warning",
      recommendation: "Revisar y eliminar warnings de pytest.",
      related_task_id: "task-qa",
      related_event_id: "event-test",
      related_file: "tests/test_health.py",
    }],
    recommendations: ["Revisar y eliminar warnings de pytest."],
    calculated_at: "2026-07-29T18:00:00Z",
    source_updated_at: "2026-07-29T17:59:59Z",
    scoring_version: "1.2",
    evidence: null,
    ...overrides,
  };
}

export function workflowSnapshot(
  overrides: Partial<WorkflowSnapshot> = {},
): WorkflowSnapshot {
  return {
    thread_id: "thread-1",
    checkpoint_id: "checkpoint-1",
    project_name: "health-api",
    workflow_intent: "create_project",
    terminal_status: "pending",
    interrupted: false,
    pending_operation: null,
    pending_tool: null,
    planning: { attempts: 1 },
    implementation: { attempts: 1 },
    testing: {},
    supervisor: { decision: "implementation" },
    created_at: null,
    updated_at: null,
    ...overrides,
  };
}

export function workflowExecution(
  overrides: Partial<WorkflowAgentExecution> = {},
): WorkflowAgentExecution {
  return {
    thread_id: "thread-1",
    branch_id: "original",
    lineage: "original",
    inherited_from: null,
    inherited_from_branch: null,
    origin_checkpoint: null,
    data_complete: true,
    workflow_intent: "create_project",
    project_name: "health-api",
    terminal_status: "completed",
    planning: {
      valid: true,
      attempts: 1,
      project_type: "FastAPI",
      framework: "FastAPI",
      analysis: {
        requirement: "Crear una API de salud.",
        objective: "Exponer GET /health.",
        functional_requirements: ["GET /health devuelve status ok"],
        non_functional_requirements: ["Pruebas automatizadas"],
        acceptance_criteria: ["La suite finaliza correctamente"],
        assumptions: [],
        constraints: [],
        risks: [],
        completed: true,
        source: "planning_result",
        updated_at: "2026-07-26T12:00:01Z",
      },
      tasks: [
        {
          task_id: "task-analysis",
          order: 1,
          agent: "Business Analyst",
          title: "Analizar requerimiento",
          description: "Identificar objetivo y criterios.",
          status: "completed",
          attempt: 1,
          result_summary: "Requerimiento validado",
          primary_event_id: "event-2",
          related_event_ids: ["event-2"],
          related_files: [],
          started_at: "2026-07-26T12:00:00Z",
          completed_at: "2026-07-26T12:00:01Z",
        },
        {
          task_id: "task-implementation",
          order: 2,
          agent: "Backend Developer",
          title: "Crear API",
          description: "Implementar el endpoint de salud.",
          status: "completed",
          attempt: 2,
          result_summary: "4 generated files",
          primary_event_id: "event-4",
          related_event_ids: ["event-4"],
          related_files: ["health_api/main.py"],
          started_at: "2026-07-26T12:00:02Z",
          completed_at: "2026-07-26T12:00:04Z",
        },
        {
          task_id: "task-testing",
          order: 3,
          agent: "QA Reviewer",
          title: "Validar proyecto",
          description: "Ejecutar pytest.",
          status: "completed",
          attempt: 1,
          result_summary: "1 passed, 2 warnings",
          primary_event_id: "event-6",
          related_event_ids: ["event-6"],
          related_files: ["tests/test_health.py"],
          started_at: "2026-07-26T12:00:05Z",
          completed_at: "2026-07-26T12:00:06Z",
        },
      ],
      validation_errors: [],
      refinements: [],
      judge: {
        status: "completed",
        model: "gpt-5-mini",
        version: "8.1-v1",
        result: {
          overall_score: 88,
          confidence: 0.91,
          dimensions: {
            requirement_alignment: 95,
            completeness: 90,
            technical_coherence: 88,
            task_clarity: 85,
            complexity_control: 82,
          },
          issues: ["Revisar si el detalle de pruebas cubre errores."],
          strengths: ["Plan alineado con el endpoint solicitado."],
          recommendation: "accept",
          reason_codes: ["semantically_aligned"],
        },
        disagreement: { detected: false, type: "aligned", delta: -2 },
        plan_fingerprint: "judge-plan-fingerprint",
        evaluated_at: "2026-07-26T12:00:01Z",
      },
      hybrid_evaluation: {
        status: "completed",
        source: "deterministic_and_judge",
        score: 89.4,
        confidence: 0.84,
        agreement: "aligned",
        dimensions: {
          requirement_coverage: {
            deterministic: 90,
            judge: 95,
            combined: 91.5,
          },
          plan_completeness: {
            deterministic: 90,
            judge: 90,
            combined: 90,
          },
        },
        flags: [],
        recommendation: "continue",
        version: "8.2-v1",
        weights: {
          deterministic_quality: 0.7,
          judge_overall: 0.3,
        },
      },
      started_at: "2026-07-26T12:00:00Z",
      completed_at: "2026-07-26T12:00:01Z",
    },
    implementation: {
      valid: true,
      attempts: 2,
      project_name: "health-api",
      package_name: "health_api",
      framework: "FastAPI",
      project_implementation: {
        project_name: "health-api",
        framework: "fastapi",
        package_name: "health_api",
      },
      generated_files: [
        "health_api/main.py",
        "tests/test_health.py",
        "pyproject.toml",
      ],
      updated_files: [],
      dependency_policy_applied: true,
      dependency_normalization_attempts: 1,
      environment_prepared: true,
      dependencies_installed: true,
      installed_dependencies: ["fastapi==0.139.0"],
      validation_errors: [],
      refinements: [{
        sequence: 3,
        stage: "implementation",
        reason: "Normalizar dependencias",
        before_summary: "fastapi",
        after_summary: "fastapi>=0.139,<0.140",
        changed_fields: ["dependencies"],
        attempt: 2,
        event_id: "event-3",
        created_at: "2026-07-26T12:00:03Z",
      }],
      started_at: "2026-07-26T12:00:02Z",
      completed_at: "2026-07-26T12:00:04Z",
    },
    testing: {
      executed: true,
      passed: true,
      framework: "pytest",
      expected_command: ["python.exe", "-m", "pytest"],
      actual_command: ["python.exe", "-m", "pytest", "-q"],
      summary: "1 passed, 2 warnings",
      warnings: 2,
      failure_type: null,
      failure_stage: null,
      failure_message: null,
      failing_test_files: [],
      repair_phase: "not_started",
      repair_attempts: 0,
      repair_decision: null,
      repair_before: null,
      repair_after: null,
      files_read_during_repair: [],
      files_updated_during_repair: [],
      started_at: "2026-07-26T12:00:05Z",
      completed_at: "2026-07-26T12:00:06Z",
    },
    agent_performance: {
      planner: {
        agent: "planner",
        status: "completed",
        score: 92,
        level: "excellent",
        confidence: 0.9,
        metrics: { validation_success: true, downstream_success: true },
        strengths: ["Planning contract validated."],
        issues: [],
        reason_codes: ["planner_evaluated"],
        version: "8.3-v1",
      },
      developer: {
        agent: "developer",
        status: "completed",
        score: 100,
        level: "excellent",
        confidence: 0.95,
        metrics: { first_pass_success: true, required_repair: false },
        strengths: ["Implementation passed tests without repair."],
        issues: [],
        reason_codes: ["developer_evaluated"],
        version: "8.3-v1",
      },
      repair: {
        agent: "repair",
        status: "not_applicable",
        score: null,
        level: null,
        confidence: 1,
        metrics: { repair_required: false },
        strengths: [],
        issues: [],
        reason_codes: ["repair_not_required"],
        version: "8.3-v1",
      },
      qa: {
        agent: "qa",
        status: "completed",
        score: 100,
        level: "excellent",
        confidence: 0.95,
        metrics: { tests_executed: true, tests_passed: true },
        strengths: ["Tests executed and produced an interpretable result."],
        issues: [],
        reason_codes: ["qa_evaluated"],
        version: "8.3-v1",
      },
    },
    failure_attribution: {
      status: "not_applicable",
      failure_class: null,
      root_cause: null,
      primary_attribution: null,
      contributors: [],
      excluded_attributions: [],
      confidence: null,
      evidence: { terminal_status: "completed", tests_passed: true },
      reason_codes: ["no_failure_detected"],
      recovered: false,
      recovery_source: null,
      causal_chain: ["planner_valid", "developer_output_created", "tests_passed"],
      version: "8.4-v1",
    },
    workflow_learning: {
      state: "submitted",
      extracted_count: 1,
      submitted_count: 1,
      duplicate_count: 0,
      rejected_count: 0,
      candidates: [{
        candidate_id: "candidate-learning-1",
        knowledge_type: "test_pattern",
        confidence: 0.95,
        submission_status: "indexed",
        knowledge_id: "knowledge-learning-1",
        source_reference: "workflow:thread-1:learning:candidate-learning-1",
        created_at: "2026-07-26T12:00:06Z",
      }],
    },
    supervisor: {
      decision: "finalize",
      decision_source: "policy",
      confidence: 0.95,
      attempts: 3,
      errors: [],
      loop_detected: false,
      handoff_history: [{
        sequence: 1,
        from: "supervisor",
        selected_to: "implementation",
        executed_to: "implementation",
        reason: "Plan listo",
      }],
    },
    final_result: {
      terminal_status: "completed",
      summary: "Proyecto health-api creado; 1 passed, 2 warnings.",
      project_created: true,
      tests_passed: true,
      failure_type: null,
      failure_message: null,
    },
    events: null,
    created_at: "2026-07-26T12:00:00Z",
    updated_at: "2026-07-26T12:00:06Z",
    ...overrides,
  };
}
